name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hisoka-multi-device"
          usedocker: true
          procfile: "worker: node . --server"
          buildpack: "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"
